### PR TITLE
Ci improvements part7

### PR DESCRIPTION
**Pull request by pavlovic-ivan**

### CODE REVIEW

**Review by jgiannuzzi — COMMENTED** [review]
I think it would now be better to add tools caching to the go-setup action and use it everywhere

**Comment by jgiannuzzi** [comment]
LGTM otherwise

**Comment by pavlovic-ivan** [comment]
> think it would now be better to add tools caching to the go-setup action and use it everywhere

I didn't check yet, but what if the go-setup action is used in many places? Do we want to restore cache where it's not needed. Especially when we want to remove that particular action, and replace it with our own

I will check where it's used of course

**Comment by jgiannuzzi** [comment]
oh I thought we had already updated everything to use our new action!

**Comment by pavlovic-ivan** [comment]
> oh I thought we had already updated everything to use our new action!

I wanted to in one of our previous PRs, but we agreed to leave it for later. I guess after this PR, we can do that, to showcase to maintainers how CI evolves, as they get used to the changes introduced iteratively. Please let me if this changes your stance for this PR

**Pull request closed without merging**
